// Code generated by whyor. DO NOT EDIT.

//go:build !whyor

package wire

import (
	context "context"
	contact "github.com/Medzoner/medzoner-go/internal/adapters/contact"
	command "github.com/Medzoner/medzoner-go/internal/application/command"
	event "github.com/Medzoner/medzoner-go/internal/application/event"
	config "github.com/Medzoner/medzoner-go/internal/config"
	articles "github.com/Medzoner/medzoner-go/internal/ui/http/articles"
	index "github.com/Medzoner/medzoner-go/internal/ui/http/index"
	database "github.com/Medzoner/medzoner-go/pkg/database"
	mocks "github.com/Medzoner/medzoner-go/test"
	captcha "github.com/medzoner-org/gomedz/pkg/captcha"
	connector "github.com/medzoner-org/gomedz/pkg/connector"
	probes "github.com/medzoner-org/gomedz/pkg/http/probes"
	server "github.com/medzoner-org/gomedz/pkg/http/server"
	logger "github.com/medzoner-org/gomedz/pkg/logger"
	notifier "github.com/medzoner-org/gomedz/pkg/notifier"
	observability "github.com/medzoner-org/gomedz/pkg/observability"
)

func InitDbMigration() (database.DbMigration, error) {
	v1, err := config.NewConfig()
	if err != nil {
		return *new(database.DbMigration), err
	}
	v2 := v1.Database
	v3 := connector.NewDbSQLInstance(v2)
	v4 := database.NewDbMigration(v3, v2)
	return v4, nil
}

func InitServerTest(ctx context.Context, m *mocks.Mocks) (server.Server, error) {
	v1, err := config.NewConfig()
	if err != nil {
		return *new(server.Server), err
	}
	v2 := v1.Logger
	v3, err := logger.NewLogger(v2)
	if err != nil {
		return *new(server.Server), err
	}
	v4 := v1.Obs
	v5, err := observability.NewTelemetry(ctx, v4, v3)
	if err != nil {
		return *new(server.Server), err
	}
	v6 := v1.Server
	v7 := v1.Auth
	v8 := middlewaresStructEmpty()
	v9 := v1.RootPath
	v10, err := newHTMLRenderer(v9)
	if err != nil {
		return *new(server.Server), err
	}
	v11 := newEngineWithRenderer(ctx, v6, v3, v7, v8, v10)
	v12 := closers(v5)
	v13 := middlewaresAny()
	v14 := pingers()
	v15 := probes.New(v6, v14)
	v16 := m.ContactRepository
	v17 := m.Mailer
	v18 := event.NewContactCreatedEventHandler(v17)
	v19 := command.NewCreateContactHandler(v16, v18)
	v20 := newValidator()
	v21 := v1.Recaptcha
	v22 := captcha.NewRecaptchaAdapter(v21)
	v23 := index.NewIndexHandler(v19, v20, v22, v9)
	v24 := articles.NewHandler()
	v25 := controllers(v15, v23, v24)
	v26 := newServer(ctx, v3, v5, v6, v11, v12, v13, v25)
	return v26, nil
}

func InitServer(ctx context.Context) (server.Server, error) {
	v1, err := config.NewConfig()
	if err != nil {
		return *new(server.Server), err
	}
	v2 := v1.Logger
	v3, err := logger.NewLogger(v2)
	if err != nil {
		return *new(server.Server), err
	}
	v4 := v1.Obs
	v5, err := observability.NewTelemetry(ctx, v4, v3)
	if err != nil {
		return *new(server.Server), err
	}
	v6 := v1.Server
	v7 := v1.Auth
	v8 := middlewaresStructEmpty()
	v9 := v1.RootPath
	v10, err := newHTMLRenderer(v9)
	if err != nil {
		return *new(server.Server), err
	}
	v11 := newEngineWithRenderer(ctx, v6, v3, v7, v8, v10)
	v12 := closers(v5)
	v13 := middlewaresAny()
	v14 := pingers()
	v15 := probes.New(v6, v14)
	v16 := v1.Database
	v17 := connector.NewDbSQLInstance(v16)
	v18 := contact.NewRepository(v17)
	v19 := v1.Mailer
	v20 := notifier.NewMailerSMTP(v19)
	v21 := event.NewContactCreatedEventHandler(v20)
	v22 := command.NewCreateContactHandler(v18, v21)
	v23 := newValidator()
	v24 := v1.Recaptcha
	v25 := captcha.NewRecaptchaAdapter(v24)
	v26 := index.NewIndexHandler(v22, v23, v25, v9)
	v27 := articles.NewHandler()
	v28 := controllers(v15, v26, v27)
	v29 := newServer(ctx, v3, v5, v6, v11, v12, v13, v28)
	return v29, nil
}
