// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/Medzoner/gomedz/pkg/auth"
	"github.com/Medzoner/gomedz/pkg/captcha"
	"github.com/Medzoner/gomedz/pkg/connector"
	"github.com/Medzoner/gomedz/pkg/http"
	"github.com/Medzoner/gomedz/pkg/http/adapter/fiber"
	"github.com/Medzoner/gomedz/pkg/http/probes"
	"github.com/Medzoner/gomedz/pkg/http/server"
	"github.com/Medzoner/gomedz/pkg/logger"
	"github.com/Medzoner/gomedz/pkg/notifier"
	"github.com/Medzoner/gomedz/pkg/observability"
	"github.com/Medzoner/gomedz/pkg/validation"
	"github.com/Medzoner/medzoner-go/internal/adapters/contact"
	"github.com/Medzoner/medzoner-go/internal/application/command"
	"github.com/Medzoner/medzoner-go/internal/application/event"
	"github.com/Medzoner/medzoner-go/internal/config"
	contact2 "github.com/Medzoner/medzoner-go/internal/ports/contact"
	"github.com/Medzoner/medzoner-go/internal/ui/http/index"
	"github.com/Medzoner/medzoner-go/pkg/database"
	"github.com/Medzoner/medzoner-go/test"
	mocks2 "github.com/Medzoner/medzoner-go/test/mocks"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitDbMigration() (database.DbMigration, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return database.DbMigration{}, err
	}
	connectorConfig := configConfig.Database
	dbSQLInstance := connector.NewDbSQLInstance(connectorConfig)
	dbMigration := database.NewDbMigration(dbSQLInstance, connectorConfig)
	return dbMigration, nil
}

func InitServerTest(ctx context.Context, m *mocks.Mocks) (server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return server.Server{}, err
	}
	loggerConfig := configConfig.Logger
	loggerInterface, err := logger.NewLogger(loggerConfig)
	if err != nil {
		return server.Server{}, err
	}
	observabilityConfig := configConfig.Obs
	telemetry, err := observability.NewTelemetry(ctx, observabilityConfig, loggerInterface)
	if err != nil {
		return server.Server{}, err
	}
	serverConfig := configConfig.Server
	authConfig := configConfig.Auth
	v := middlewaresStructEmpty()
	rootPath := configConfig.RootPath
	reloadingHTMLRenderer, err := newHTMLRenderer(rootPath)
	if err != nil {
		return server.Server{}, err
	}
	engine := newEngineWithRenderer(ctx, serverConfig, loggerInterface, authConfig, v, reloadingHTMLRenderer)
	v2 := closers(telemetry)
	v3 := middlewaresAny()
	probesPingers := pingers()
	handler := probes.New(serverConfig, probesPingers)
	mockRepository := m.ContactRepository
	mockMailer := m.Mailer
	contactCreatedEventHandler := event.NewContactCreatedEventHandler(mockMailer)
	createContactCommandHandler := command.NewCreateContactCommandHandler(mockRepository, contactCreatedEventHandler)
	validatorAdapter := validation.New()
	captchaConfig := configConfig.Recaptcha
	recaptchaAdapter := captcha.NewRecaptchaAdapter(captchaConfig)
	indexHandler := index.NewIndexHandler(createContactCommandHandler, validatorAdapter, recaptchaAdapter, rootPath)
	v4 := controllers(handler, indexHandler)
	serverServer := newServer(ctx, loggerInterface, telemetry, serverConfig, engine, v2, v3, v4)
	return serverServer, nil
}

func InitServer(ctx context.Context) (server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return server.Server{}, err
	}
	loggerConfig := configConfig.Logger
	loggerInterface, err := logger.NewLogger(loggerConfig)
	if err != nil {
		return server.Server{}, err
	}
	observabilityConfig := configConfig.Obs
	telemetry, err := observability.NewTelemetry(ctx, observabilityConfig, loggerInterface)
	if err != nil {
		return server.Server{}, err
	}
	serverConfig := configConfig.Server
	authConfig := configConfig.Auth
	v := middlewaresStructEmpty()
	rootPath := configConfig.RootPath
	reloadingHTMLRenderer, err := newHTMLRenderer(rootPath)
	if err != nil {
		return server.Server{}, err
	}
	engine := newEngineWithRenderer(ctx, serverConfig, loggerInterface, authConfig, v, reloadingHTMLRenderer)
	v2 := closers(telemetry)
	v3 := middlewaresAny()
	probesPingers := pingers()
	handler := probes.New(serverConfig, probesPingers)
	connectorConfig := configConfig.Database
	dbSQLInstance := connector.NewDbSQLInstance(connectorConfig)
	repository := contact.NewRepository(dbSQLInstance)
	notifierConfig := configConfig.Mailer
	mailerSMTP := notifier.NewMailerSMTP(notifierConfig)
	contactCreatedEventHandler := event.NewContactCreatedEventHandler(mailerSMTP)
	createContactCommandHandler := command.NewCreateContactCommandHandler(repository, contactCreatedEventHandler)
	validatorAdapter := validation.New()
	captchaConfig := configConfig.Recaptcha
	recaptchaAdapter := captcha.NewRecaptchaAdapter(captchaConfig)
	indexHandler := index.NewIndexHandler(createContactCommandHandler, validatorAdapter, recaptchaAdapter, rootPath)
	v4 := controllers(handler, indexHandler)
	serverServer := newServer(ctx, loggerInterface, telemetry, serverConfig, engine, v2, v3, v4)
	return serverServer, nil
}

// wire.go:

func controllers(p *probes.Handler, a index.Handler) []http.Controller {
	return []http.Controller{
		p,
		a,
	}
}

func closers(tl observability.Telemetry) []server.Closer {
	return []server.Closer{
		tl,
	}
}

func pingers() probes.Pingers {
	return []probes.Probes{}
}

func middlewaresStructEmpty() []http.Middleware[struct{}] {
	return []http.Middleware[struct{}]{}
}

func middlewaresAny() []http.Middleware[any] {
	return []http.Middleware[any]{}
}

func newEngineWithRenderer(ctx context.Context, cfg server.Config, l logger.Interface, authCfg auth.Config, mdrs []http.Middleware[struct{}], renderer *http.ReloadingHTMLRenderer) *fiber.Engine[any] {
	engine := fiber.New(ctx, cfg, l, authCfg, mdrs)
	engine.SetRenderer(renderer)
	return engine
}

func newServer(
	ctx context.Context,
	log logger.Interface,
	tel observability.Telemetry,
	cfg server.Config,
	engine server.Enginer, closers2 []server.Closer,
	mdwrs []http.Middleware[any], controllers2 []http.Controller,
) server.Server {
	s := server.NewServer(ctx, log, tel, cfg, engine, closers2, mdwrs, controllers2...)

	engine.SetNotFoundHandler(http.DefaultNotFoundHandler("404"))

	return s
}

func newHTMLRenderer(rootPath config.RootPath) (*http.ReloadingHTMLRenderer, error) {
	base := string(rootPath) + "tmpl"
	renderer := http.NewReloadingHTMLRenderer(base)

	return renderer, nil
}

var (
	CommonWiring = wire.NewSet(config.NewConfig, wire.FieldsOf(
		new(config.Config),
		"Obs",
		"Engine",
		"Logger",
		"Auth",
		"Server",
		"Mailer",
		"Database",
		"Recaptcha",
		"RootPath",
	), pingers, probes.New,
	)
	ServerWiring = wire.NewSet(
		newHTMLRenderer, wire.Bind(new(http.Renderer), new(*http.ReloadingHTMLRenderer)), newEngineWithRenderer, wire.Bind(new(server.Enginer), new(*fiber.Engine[any])), controllers,
		closers,
		middlewaresStructEmpty,
		middlewaresAny,

		newServer,
	)
	ObsWiring     = wire.NewSet(logger.NewLogger, observability.NewTelemetry)
	UsecaseWiring = wire.NewSet(event.NewContactCreatedEventHandler, command.NewCreateContactCommandHandler, wire.Bind(new(event.Handler), new(*event.ContactCreatedEventHandler)))
	HandlerWiring = wire.NewSet(index.NewIndexHandler)

	InfraWiring      = wire.NewSet(validation.New, captcha.NewRecaptchaAdapter, wire.Bind(new(validation.Validater), new(*validation.ValidatorAdapter)), wire.Bind(new(captcha.Captcher), new(*captcha.RecaptchaAdapter)))
	DbWiring         = wire.NewSet(connector.NewDbSQLInstance, wire.Bind(new(connector.DbInstantiator), new(*connector.DbSQLInstance)))
	MailerWiring     = wire.NewSet(notifier.NewMailerSMTP, wire.Bind(new(event.Mailer), new(*notifier.MailerSMTP)))
	MailerMockWiring = wire.NewSet(wire.FieldsOf(
		new(*mocks.Mocks),
		"Mailer",
	), wire.Bind(new(event.Mailer), new(*mocks2.MockMailer)),
	)
	RepositoryWiring     = wire.NewSet(contact.NewRepository, wire.Bind(new(contact2.Repository), new(*contact.Repository)))
	RepositoryMockWiring = wire.NewSet(wire.FieldsOf(
		new(*mocks.Mocks),
		"ContactRepository",
	), wire.Bind(new(contact2.Repository), new(*mocks2.MockRepository)),
	)
	AppWiring = wire.NewSet(event.NewContactCreatedEventHandler, command.NewCreateContactCommandHandler, wire.Bind(new(event.Handler), new(*event.ContactCreatedEventHandler)))
	UiWiring  = wire.NewSet(index.NewIndexHandler)
)
