// Code generated by hand (mock). DO NOT EDIT.

package mocks

import (
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockCaptcher is a mock of Captcher interface.
type MockCaptcher struct {
	ctrl     *gomock.Controller
	recorder *MockCaptcherMockRecorder
}

// MockCaptcherMockRecorder is the mock recorder for MockCaptcher.
type MockCaptcherMockRecorder struct {
	mock *MockCaptcher
}

// NewMockCaptcher creates a new mock instance.
func NewMockCaptcher(ctrl *gomock.Controller) *MockCaptcher {
	mock := &MockCaptcher{ctrl: ctrl}
	mock.recorder = &MockCaptcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptcher) EXPECT() *MockCaptcherMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockCaptcher) Confirm(remoteIP, resp string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", remoteIP, resp)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockCaptcherMockRecorder) Confirm(remoteIP, resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockCaptcher)(nil).Confirm), remoteIP, resp)
}

// GetSiteKey mocks base method.
func (m *MockCaptcher) GetSiteKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSiteKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSiteKey indicates an expected call of GetSiteKey.
func (mr *MockCaptcherMockRecorder) GetSiteKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSiteKey", reflect.TypeOf((*MockCaptcher)(nil).GetSiteKey))
}

// GetSecretKey mocks base method.
func (m *MockCaptcher) GetSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecretKey indicates an expected call of GetSecretKey.
func (mr *MockCaptcherMockRecorder) GetSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretKey", reflect.TypeOf((*MockCaptcher)(nil).GetSecretKey))
}

