// Code generated by hand (mock). DO NOT EDIT.

package mocks

import (
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockValidater is a mock of Validater interface.
type MockValidater struct {
	ctrl     *gomock.Controller
	recorder *MockValidaterMockRecorder
}

// MockValidaterMockRecorder is the mock recorder for MockValidater.
type MockValidaterMockRecorder struct {
	mock *MockValidater
}

// NewMockValidater creates a new mock instance.
func NewMockValidater(ctrl *gomock.Controller) *MockValidater {
	mock := &MockValidater{ctrl: ctrl}
	mock.recorder = &MockValidaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidater) EXPECT() *MockValidaterMockRecorder {
	return m.recorder
}

// Struct mocks base method.
func (m *MockValidater) Struct(obj any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Struct", obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Struct indicates an expected call of Struct.
func (mr *MockValidaterMockRecorder) Struct(obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Struct", reflect.TypeOf((*MockValidater)(nil).Struct), obj)
}

// StructCtx mocks base method.
func (m *MockValidater) StructCtx(ctx context.Context, s interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StructCtx", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// StructCtx indicates an expected call of StructCtx.
func (mr *MockValidaterMockRecorder) StructCtx(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StructCtx", reflect.TypeOf((*MockValidater)(nil).StructCtx), ctx, s)
}

